services:
  - type: web
    name: hybrid-reddit-api
    env: python
    runtime: docker
    plan: free
    dockerfilePath: Scripts/Dockerfile
    autoDeploy: false
    buildFilter:
      paths:
        - Scripts/Dockerfile
        - Scripts/requirements.txt
        - Scripts/main.py
        - Scripts/Retrieval.py
        - Scripts/*.py
        - Scripts/*.ipynb
        - FAISS/**
        - Elasticsearch/**
    envVars:
      - key: PORT
        value: 8000
